# Generated by Django 6.0.2 on 2026-03-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=50)),
                ("mail", models.EmailField(max_length=254)),
                ("texto", models.TextField()),
                (
                    "producto",
                    models.CharField(
                        choices=[
                            ("prevencion", "Prevención y Controles"),
                            ("bebe", "Primera Consulta del Bebé"),
                            ("restauradores", "Tratamientos Restauradores"),
                            ("sin_miedo", "Odontología sin Miedo"),
                            ("educacion", "Educación y Hábitos"),
                            ("general", "Consulta General"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("google_ads", "Google Ads"),
                            ("facebook_ads", "Facebook / Instagram Ads"),
                            ("organico", "Búsqueda Orgánica"),
                            ("whatsapp", "WhatsApp"),
                            ("directo", "Tráfico Directo"),
                        ],
                        default="directo",
                        max_length=50,
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "utm_medium",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "utm_campaign",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "utm_content",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("utm_term", models.CharField(blank=True, default="", max_length=100)),
                ("gclid", models.CharField(blank=True, default="", max_length=255)),
                ("fbclid", models.CharField(blank=True, default="", max_length=255)),
                (
                    "landing_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
