# Generated by Django 6.0.2 on 2026-03-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turnos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesional",
            name="duracion_turno_minutos",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="profesional",
            name="especialidad",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
